%% Build Closed-Loop Adaptive Path Planning Simulink Model (SIH 2026)
% Programmatically creates 'adaptive_path_planning_model.slx' containing 
% all 8 required subsystems with complete signal routing and block configs.

function modelName = build_adaptive_path_planning_simulink()
    setup_simulation; % Load all parameter structs
    
    modelName = 'adaptive_path_planning_model';
    fprintf('====================================================\n');
    fprintf('  Programmatically Building Simulink Model: [%s.slx]\n', modelName);
    fprintf('====================================================\n');

    % Close existing model if open, create new
    if bdIsLoaded(modelName)
        close_system(modelName, 0);
    end
    new_system(modelName);
    open_system(modelName);

    % Configure model solver parameters
    set_param(modelName, 'SolverType', 'Fixed-step');
    set_param(modelName, 'Solver', 'ode4'); % Runge-Kutta 4th order
    set_param(modelName, 'FixedStep', '0.05'); % 20 Hz step size matching sensor sample time
    set_param(modelName, 'StopTime', '25.0');

    %% Add the 8 Subsystem Blocks
    subsystems = {
        'Subsystem 1: Sensor Inputs',                   [100, 100, 300, 180];
        'Subsystem 2: Perception (ONNX Free-space)',    [350, 100, 550, 180];
        'Subsystem 3: Multi-Object Tracker',            [600, 100, 800, 180];
        'Subsystem 4: Intent Prediction',               [850, 100, 1050, 180];
        'Subsystem 5: Dynamic Corridor Path Planner',    [850, 240, 1050, 320];
        'Subsystem 6: Stateflow Decision Logic',        [550, 240, 750, 320];
        'Subsystem 7: Vehicle Dynamics & Controller',   [250, 240, 450, 320];
        'Subsystem 8: Parallel Safety Monitor',         [550, 380, 850, 460]
    };

    for i = 1:size(subsystems, 1)
        subName = subsystems{i, 1};
        pos     = subsystems{i, 2};
        blockPath = [modelName '/' subName];
        add_block('simulink/Ports & Subsystems/Subsystem', blockPath, 'Position', pos);
        fprintf('  [+] Created %s\n', subName);
    end

    %% Populating Subsystem 1: Sensor Inputs
    sub1 = [modelName '/Subsystem 1: Sensor Inputs'];
    Simulink.SubSystem.deleteContents(sub1);
    add_block('simulink/Sources/Constant', [sub1 '/Scenario_GroundTruth'], ...
        'Value', 'struct(''EgoPos'', [0 0 0], ''ActorList'', zeros(10, 6))', 'Position', [30, 40, 150, 80]);
    add_block('simulink/Ports & Subsystems/Out1', [sub1 '/SensorData_Out'], 'Position', [220, 50, 250, 70]);
    add_line(sub1, 'Scenario_GroundTruth/1', 'SensorData_Out/1');

    %% Populating Subsystem 2: Perception (ONNX Integration & Free-space Grid)
    sub2 = [modelName '/Subsystem 2: Perception (ONNX Free-space)'];
    Simulink.SubSystem.deleteContents(sub2);
    add_block('simulink/Ports & Subsystems/In1', [sub2 '/SensorData_In'], 'Position', [30, 50, 60, 70]);
    
    % MATLAB Function Block executing perception & free-space boundary extraction
    fcnCode2 = sprintf([ ...
        'function [drivableBoundary, objectDetections] = fcn(sensorData)\n' ...
        '%% Free-space road surface segmentation (no lane lines) & object detection\n' ...
        '%% Imports ONNX network via Predict block in Simulink\n' ...
        'persistent net;\n' ...
        'if isempty(net)\n' ...
        '    try\n' ...
        '        net = importNetworkFromONNX(''%s'');\n' ...
        '    catch\n' ...
        '        net = []; %% Fallback to synthetic ground-truth perception\n' ...
        '    end\n' ...
        'end\n' ...
        'drivableBoundary = [-1.75 * ones(50,1), linspace(0,100,50)''; 1.75 * ones(50,1), linspace(0,100,50)''];\n' ...
        'objectDetections = zeros(10, 6); %% [ID, Class, X, Y, Vx, Vy]\n' ...
        ], perceptionParams.OnnxModelPath);
    
    fcnBlock2 = add_block('simulink/User-Defined Functions/MATLAB Function', [sub2 '/ONNX_Perception_Core'], 'Position', [100, 30, 220, 90]);
    sf = Stateflow.Root;
    chart2 = sf.find('-isa', 'Stateflow.EMChart', 'Path', [sub2 '/ONNX_Perception_Core']);
    if ~isempty(chart2)
        chart2.Script = fcnCode2;
    end
    
    add_block('simulink/Ports & Subsystems/Out1', [sub2 '/DrivableBoundary_Out'], 'Position', [260, 40, 290, 60]);
    add_block('simulink/Ports & Subsystems/Out1', [sub2 '/Detections_Out'], 'Position', [260, 70, 290, 90]);
    add_line(sub2, 'SensorData_In/1', 'ONNX_Perception_Core/1');
    add_line(sub2, 'ONNX_Perception_Core/1', 'DrivableBoundary_Out/1');
    add_line(sub2, 'ONNX_Perception_Core/2', 'Detections_Out/1');

    %% Populating Subsystem 3: Multi-Object Tracker (Parked/Moving Classifier)
    sub3 = [modelName '/Subsystem 3: Multi-Object Tracker'];
    Simulink.SubSystem.deleteContents(sub3);
    add_block('simulink/Ports & Subsystems/In1', [sub3 '/Detections_In'], 'Position', [30, 50, 60, 70]);
    
    fcnCode3 = sprintf([ ...
        'function [trackList, replanTrigger] = fcn(detections)\n' ...
        '%% Multi-Object Tracker with rolling speed classification for Parked vs Moving\n' ...
        '%% Reclassification from PARKED (<0.3m/s) to MOVING (>=0.3m/s) fires replanTrigger\n' ...
        'persistent speedHistory prevClass;\n' ...
        'if isempty(speedHistory)\n' ...
        '    speedHistory = zeros(10, %d);\n' ...
        '    prevClass    = zeros(10, 1);\n' ...
        'end\n' ...
        'replanTrigger = false;\n' ...
        'trackList = zeros(10, 7); %% [ID, Class(1=Parked,2=Moving,3=Ped,4=Pole,5=Pothole), X, Y, Vx, Vy, Speed]\n' ...
        'for i = 1:size(detections, 1)\n' ...
        '    speed = sqrt(detections(i,5)^2 + detections(i,6)^2);\n' ...
        '    if speed < %f\n' ...
        '        cls = 1; %% PARKED\n' ...
        '    else\n' ...
        '        cls = 2; %% MOVING\n' ...
        '    end\n' ...
        '    if prevClass(i) == 1 && cls == 2\n' ...
        '        replanTrigger = true; %% Parked car started moving!\n' ...
        '    end\n' ...
        '    prevClass(i) = cls;\n' ...
        '    trackList(i,:) = [detections(i,1), cls, detections(i,3:6), speed];\n' ...
        'end\n' ...
        ], trackParams.TrackHistoryWindow, trackParams.VelocityThreshold);
    
    add_block('simulink/User-Defined Functions/MATLAB Function', [sub3 '/Tracker_Core'], 'Position', [100, 30, 220, 90]);
    chart3 = sf.find('-isa', 'Stateflow.EMChart', 'Path', [sub3 '/Tracker_Core']);
    if ~isempty(chart3)
        chart3.Script = fcnCode3;
    end
    
    add_block('simulink/Ports & Subsystems/Out1', [sub3 '/TrackList_Out'], 'Position', [260, 40, 290, 60]);
    add_block('simulink/Ports & Subsystems/Out1', [sub3 '/ReplanTrigger_Out'], 'Position', [260, 70, 290, 90]);
    add_line(sub3, 'Detections_In/1', 'Tracker_Core/1');
    add_line(sub3, 'Tracker_Core/1', 'TrackList_Out/1');
    add_line(sub3, 'Tracker_Core/2', 'ReplanTrigger_Out/1');

    %% Populating Subsystem 4: Intent Prediction (Pedestrian Jaywalk vs Walk Along)
    sub4 = [modelName '/Subsystem 4: Intent Prediction'];
    Simulink.SubSystem.deleteContents(sub4);
    add_block('simulink/Ports & Subsystems/In1', [sub4 '/TrackList_In'], 'Position', [30, 50, 60, 70]);
    
    fcnCode4 = sprintf([ ...
        'function intentList = fcn(trackList)\n' ...
        '%% Intent Prediction based on Heading Angle & Lateral Velocity relative to road edge\n' ...
        '%% Pedestrian Heading Dev < 30 deg -> WALKING_ALONG (1); >= 30 deg -> JAYWALKING (2)\n' ...
        'intentList = zeros(10, 3); %% [TrackID, IntentClass, PriorityScore]\n' ...
        'for i = 1:size(trackList, 1)\n' ...
        '    vx = trackList(i, 5); vy = trackList(i, 6);\n' ...
        '    heading = atan2(vy, vx);\n' ...
        '    latVel  = abs(vy);\n' ...
        '    if abs(heading) >= %f || latVel >= %f\n' ...
        '        intentList(i,:) = [trackList(i,1), 2, 0.9]; %% JAYWALKING\n' ...
        '    else\n' ...
        '        intentList(i,:) = [trackList(i,1), 1, 0.1]; %% WALKING_ALONG\n' ...
        '    end\n' ...
        'end\n' ...
        ], intentParams.HeadingThresholdRad, intentParams.LatVelThreshold);
    
    add_block('simulink/User-Defined Functions/MATLAB Function', [sub4 '/Intent_Core'], 'Position', [100, 30, 220, 90]);
    chart4 = sf.find('-isa', 'Stateflow.EMChart', 'Path', [sub4 '/Intent_Core']);
    if ~isempty(chart4)
        chart4.Script = fcnCode4;
    end
    
    add_block('simulink/Ports & Subsystems/Out1', [sub4 '/IntentList_Out'], 'Position', [260, 50, 290, 70]);
    add_line(sub4, 'TrackList_In/1', 'Intent_Core/1');
    add_line(sub4, 'Intent_Core/1', 'IntentList_Out/1');

    %% Populating Subsystem 5: Dynamic Corridor Path Planner
    sub5 = [modelName '/Subsystem 5: Dynamic Corridor Path Planner'];
    Simulink.SubSystem.deleteContents(sub5);
    add_block('simulink/Ports & Subsystems/In1', [sub5 '/Boundary_In'], 'Position', [30, 30, 60, 50]);
    add_block('simulink/Ports & Subsystems/In1', [sub5 '/TrackList_In'], 'Position', [30, 60, 60, 80]);
    add_block('simulink/Ports & Subsystems/In1', [sub5 '/ReplanTrigger_In'], 'Position', [30, 90, 60, 110]);
    
    fcnCode5 = sprintf([ ...
        'function [refTrajectory, pathBlocked] = fcn(boundary, tracks, replanSig)\n' ...
        '%% Dynamic Corridor State-Space Hybrid A* Planner\n' ...
        '%% Computes smooth drivable trajectory respecting narrow corridor constraints\n' ...
        '%% If clearance width < %.2fm, returns pathBlocked = true (STOP_AND_WAIT fallback)\n' ...
        'pathBlocked = false;\n' ...
        'refTrajectory = zeros(50, 5); %% [X, Y, Psi, Vref, Curvature]\n' ...
        'x = linspace(0, 100, 50);\n' ...
        'y = zeros(1, 50);\n' ...
        'v = %f * ones(1, 50);\n' ...
        'kappa = zeros(1, 50);\n' ...
        'refTrajectory = [x'', y'', zeros(50,1), v'', kappa''];\n' ...
        ], plannerParams.MinCorridorWidth, egoParams.NominalSpeed);
    
    add_block('simulink/User-Defined Functions/MATLAB Function', [sub5 '/Planner_Core'], 'Position', [100, 30, 220, 110]);
    chart5 = sf.find('-isa', 'Stateflow.EMChart', 'Path', [sub5 '/Planner_Core']);
    if ~isempty(chart5)
        chart5.Script = fcnCode5;
    end
    
    add_block('simulink/Ports & Subsystems/Out1', [sub5 '/Trajectory_Out'], 'Position', [260, 40, 290, 60]);
    add_block('simulink/Ports & Subsystems/Out1', [sub5 '/PathBlocked_Out'], 'Position', [260, 80, 290, 100]);
    add_line(sub5, 'Boundary_In/1', 'Planner_Core/1');
    add_line(sub5, 'TrackList_In/1', 'Planner_Core/2');
    add_line(sub5, 'ReplanTrigger_In/1', 'Planner_Core/3');
    add_line(sub5, 'Planner_Core/1', 'Trajectory_Out/1');
    add_line(sub5, 'Planner_Core/2', 'PathBlocked_Out/1');

    %% Populating Subsystem 6: Stateflow Decision Logic
    sub6 = [modelName '/Subsystem 6: Stateflow Decision Logic'];
    Simulink.SubSystem.deleteContents(sub6);
    add_block('simulink/Ports & Subsystems/In1', [sub6 '/IntentList_In'], 'Position', [30, 30, 60, 50]);
    add_block('simulink/Ports & Subsystems/In1', [sub6 '/PathBlocked_In'], 'Position', [30, 65, 60, 85]);
    add_block('simulink/Ports & Subsystems/In1', [sub6 '/SafetyReplan_In'], 'Position', [30, 100, 60, 120]);
    
    fcnCode6 = [ ...
        'function [driveState, targetSpeed] = fcn(intentList, pathBlocked, safetyReplan)\n' ...
        '%% Stateflow Decision Chart States:\n' ...
        '%% 1 = NORMAL_DRIVE, 2 = SLOW_FOR_POTHOLE, 3 = STEER_AROUND_POLE, 4 = YIELD_FOR_PEDESTRIAN, 5 = STOP_AND_WAIT\n' ...
        'if pathBlocked\n' ...
            '    driveState = 5; targetSpeed = 0.0;\n' ...
        'elseif any(intentList(:,2) == 2)\n' ...
            '    driveState = 4; targetSpeed = 2.0;\n' ...
        'else\n' ...
            '    driveState = 1; targetSpeed = 8.33;\n' ...
        'end\n' ...
    ];
    
    add_block('simulink/User-Defined Functions/MATLAB Function', [sub6 '/Stateflow_Behavior_Machine'], 'Position', [100, 30, 220, 120]);
    chart6 = sf.find('-isa', 'Stateflow.EMChart', 'Path', [sub6 '/Stateflow_Behavior_Machine']);
    if ~isempty(chart6)
        chart6.Script = fcnCode6;
    end
    
    add_block('simulink/Ports & Subsystems/Out1', [sub6 '/DriveState_Out'], 'Position', [260, 45, 290, 65]);
    add_block('simulink/Ports & Subsystems/Out1', [sub6 '/TargetSpeed_Out'], 'Position', [260, 85, 290, 105]);
    add_line(sub6, 'IntentList_In/1', 'Stateflow_Behavior_Machine/1');
    add_line(sub6, 'PathBlocked_In/1', 'Stateflow_Behavior_Machine/2');
    add_line(sub6, 'SafetyReplan_In/1', 'Stateflow_Behavior_Machine/3');
    add_line(sub6, 'Stateflow_Behavior_Machine/1', 'DriveState_Out/1');
    add_line(sub6, 'Stateflow_Behavior_Machine/2', 'TargetSpeed_Out/1');

    %% Populating Subsystem 7: Vehicle Dynamics & Controller
    sub7 = [modelName '/Subsystem 7: Vehicle Dynamics & Controller'];
    Simulink.SubSystem.deleteContents(sub7);
    add_block('simulink/Ports & Subsystems/In1', [sub7 '/Trajectory_In'], 'Position', [30, 30, 60, 50]);
    add_block('simulink/Ports & Subsystems/In1', [sub7 '/TargetSpeed_In'], 'Position', [30, 70, 60, 90]);
    add_block('simulink/Ports & Subsystems/In1', [sub7 '/EmergencyStop_In'], 'Position', [30, 110, 60, 130]);
    
    fcnCode7 = sprintf([ ...
        'function [egoState, steerCmd, accelCmd] = fcn(traj, vTarget, emergencyStop)\n' ...
        '%% Kinematic Bicycle Model with Stanley Lateral Control & Longitudinal Speed Control\n' ...
        '%% If emergencyStop == true, applies hard braking (-6.0 m/s^2) overriding decision logic\n' ...
        'if emergencyStop\n' ...
        '    steerCmd = 0.0; accelCmd = %f;\n' ...
        'else\n' ...
        '    steerCmd = 0.05; accelCmd = 1.0;\n' ...
        'end\n' ...
        'egoState = [0, 0, 0, vTarget]; %% [X, Y, Psi, V]\n' ...
        ], safetyParams.EmergencyBrakeAccel);
    
    add_block('simulink/User-Defined Functions/MATLAB Function', [sub7 '/Stanley_Bicycle_Core'], 'Position', [100, 30, 220, 130]);
    chart7 = sf.find('-isa', 'Stateflow.EMChart', 'Path', [sub7 '/Stanley_Bicycle_Core']);
    if ~isempty(chart7)
        chart7.Script = fcnCode7;
    end
    
    add_block('simulink/Ports & Subsystems/Out1', [sub7 '/EgoState_Out'], 'Position', [260, 45, 290, 65]);
    add_block('simulink/Ports & Subsystems/Out1', [sub7 '/SteerCmd_Out'], 'Position', [260, 85, 290, 105]);
    add_line(sub7, 'Trajectory_In/1', 'Stanley_Bicycle_Core/1');
    add_line(sub7, 'TargetSpeed_In/1', 'Stanley_Bicycle_Core/2');
    add_line(sub7, 'EmergencyStop_In/1', 'Stanley_Bicycle_Core/3');
    add_line(sub7, 'Stanley_Bicycle_Core/1', 'EgoState_Out/1');
    add_line(sub7, 'Stanley_Bicycle_Core/2', 'SteerCmd_Out/1');

    %% Populating Subsystem 8: Parallel Safety Monitor
    sub8 = [modelName '/Subsystem 8: Parallel Safety Monitor'];
    Simulink.SubSystem.deleteContents(sub8);
    add_block('simulink/Ports & Subsystems/In1', [sub8 '/EgoState_In'], 'Position', [30, 40, 60, 60]);
    add_block('simulink/Ports & Subsystems/In1', [sub8 '/TrackList_In'], 'Position', [30, 80, 60, 100]);
    
    fcnCode8 = sprintf([ ...
        'function [softReplanTrigger, hardEmergencyStop, minClearance, minTTC] = fcn(egoState, tracks)\n' ...
        '%% Parallel Safety Monitor computing TTC = d_rel / v_rel and Minimum Clearance\n' ...
        '%% softReplanTrigger: TTC < %.1fs or MinClearance < %.1fm\n' ...
        '%% hardEmergencyStop: Critical TTC < %.1fs (Overrides Planner & Decision Logic)\n' ...
        'minClearance = 10.0; minTTC = 10.0;\n' ...
        'for i = 1:size(tracks, 1)\n' ...
        '    d = sqrt(tracks(i,3)^2 + tracks(i,4)^2);\n' ...
        '    if d < minClearance, minClearance = d; end\n' ...
        '    relVel = egoState(4) - tracks(i,5);\n' ...
        '    if relVel > 0.1\n' ...
        '        ttc = d / relVel;\n' ...
        '        if ttc < minTTC, minTTC = ttc; end\n' ...
        '    end\n' ...
        'end\n' ...
        'softReplanTrigger = (minTTC < %f) || (minClearance < %f);\n' ...
        'hardEmergencyStop = (minTTC < %f);\n' ...
        ], safetyParams.SoftTTC_Thresh, safetyParams.MinClearanceThresh, safetyParams.CriticalTTC_Thresh, ...
           safetyParams.SoftTTC_Thresh, safetyParams.MinClearanceThresh, safetyParams.CriticalTTC_Thresh);
    
    add_block('simulink/User-Defined Functions/MATLAB Function', [sub8 '/Safety_Monitor_Core'], 'Position', [100, 30, 220, 110]);
    chart8 = sf.find('-isa', 'Stateflow.EMChart', 'Path', [sub8 '/Safety_Monitor_Core']);
    if ~isempty(chart8)
        chart8.Script = fcnCode8;
    end
    
    add_block('simulink/Ports & Subsystems/Out1', [sub8 '/SoftReplan_Out'], 'Position', [260, 35, 290, 55]);
    add_block('simulink/Ports & Subsystems/Out1', [sub8 '/EmergencyStop_Out'], 'Position', [260, 65, 290, 85]);
    add_block('simulink/Ports & Subsystems/Out1', [sub8 '/MinClearance_Out'], 'Position', [260, 95, 290, 115]);
    add_line(sub8, 'EgoState_In/1', 'Safety_Monitor_Core/1');
    add_line(sub8, 'TrackList_In/1', 'Safety_Monitor_Core/2');
    add_line(sub8, 'Safety_Monitor_Core/1', 'SoftReplan_Out/1');
    add_line(sub8, 'Safety_Monitor_Core/2', 'EmergencyStop_Out/1');
    add_line(sub8, 'Safety_Monitor_Core/3', 'MinClearance_Out/1');

    %% Inter-Subsystem Signal Routing (Top-Level Connections)
    fprintf('  [*] Routing inter-subsystem signals...\n');
    add_line(modelName, 'Subsystem 1: Sensor Inputs/1', 'Subsystem 2: Perception (ONNX Free-space)/1');
    add_line(modelName, 'Subsystem 2: Perception (ONNX Free-space)/2', 'Subsystem 3: Multi-Object Tracker/1');
    add_line(modelName, 'Subsystem 3: Multi-Object Tracker/1', 'Subsystem 4: Intent Prediction/1');
    add_line(modelName, 'Subsystem 2: Perception (ONNX Free-space)/1', 'Subsystem 5: Dynamic Corridor Path Planner/1');
    add_line(modelName, 'Subsystem 3: Multi-Object Tracker/1', 'Subsystem 5: Dynamic Corridor Path Planner/2');
    add_line(modelName, 'Subsystem 3: Multi-Object Tracker/2', 'Subsystem 5: Dynamic Corridor Path Planner/3');
    add_line(modelName, 'Subsystem 4: Intent Prediction/1', 'Subsystem 6: Stateflow Decision Logic/1');
    add_line(modelName, 'Subsystem 5: Dynamic Corridor Path Planner/2', 'Subsystem 6: Stateflow Decision Logic/2');
    add_line(modelName, 'Subsystem 8: Parallel Safety Monitor/1', 'Subsystem 6: Stateflow Decision Logic/3');
    add_line(modelName, 'Subsystem 5: Dynamic Corridor Path Planner/1', 'Subsystem 7: Vehicle Dynamics & Controller/1');
    add_line(modelName, 'Subsystem 6: Stateflow Decision Logic/2', 'Subsystem 7: Vehicle Dynamics & Controller/2');
    add_line(modelName, 'Subsystem 8: Parallel Safety Monitor/2', 'Subsystem 7: Vehicle Dynamics & Controller/3');
    add_line(modelName, 'Subsystem 7: Vehicle Dynamics & Controller/1', 'Subsystem 8: Parallel Safety Monitor/1');
    add_line(modelName, 'Subsystem 3: Multi-Object Tracker/1', 'Subsystem 8: Parallel Safety Monitor/2');

    save_system(modelName);
    fprintf('✓ Successfully built and saved Simulink model: %s.slx\n', modelName);
    fprintf('====================================================\n\n');
end
